
  name: AltBlu Github Pages Deploy Staging

  on: [push, pull_request]

  env:
    SSR: false
    TARGET: static
    FETCH: false

  jobs:
    cd:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [14]

      steps:
        - name: Checkout Code
          uses: actions/checkout@master

        - name: Environment Setup
          uses: actions/setup-node@v2.1.2
          with:
            node-version: ${{ matrix.node }}

        - name: Install Dependencies
          run: npm install

        - name: Generate Website
          run: npm run generate

        - name: Deploy Website
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist

        - name: Webhook
          uses: distributhor/workflow-webhook@v2
          env:
            webhook_url: "https://altblu-app.herokuapp.com/api/v1/website/github/webhook"
            webhook_secret: "${{ secrets.GH_WEBHOOK_SECRET }}"
            data: '{ "email": "riley@altblu.com", "tenant" : "6063e961487586b53cf0310b", "repo" : "Riley-/nuxt-git-test", "domain" : "basds.altblu.com", "owner" : "Riley-", "name" : "nuxt-git-test"}'
  