
  name: AltBlu S3 Deploy Production

  on: repository_dispatch

  env:
    SSR: true
    TARGET: static
    FETCH: true

  jobs:
    cd:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [14]

      steps:
        - name: Checkout Code
          uses: actions/checkout@master

        - name: Environment Setup
          uses: actions/setup-node@v2.1.2
          with:
            node-version: ${{ matrix.node }}

        - name: Install Dependencies
          run: npm install

        - name: Generate Website
          run: npm run generate

        - name: Deploy Static Website to S3
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: undefined
            bucket-region: us-west-2

        - name: Webhook
          uses: distributhor/workflow-webhook@v2
          env:
            webhook_url: "https://altblu-app.herokuapp.com/api/v1/website/github/webhook"
            webhook_secret: "Emery and Charley are perfect!"
            data: '{ "email": "riley@altblu.com", "tenant" : "6063e961487586b53cf0310b", "repo" : "Riley-/nuxt-git-test", "domain" : "boonies.altblu.com", "owner" : "Riley-", "name" : "nuxt-git-test"}'
  