
  name: AltBlu S3 Deploy Production [Dispatch]

  on:
    repository_dispatch:
      types: [production, push, build]

  env:
    SSR: true
    TARGET: static
    FETCH: true
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  jobs:
    cd:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [14]

      steps:
        - name: Checkout Code
          uses: actions/checkout@master

        - name: Environment Setup
          uses: actions/setup-node@v2.1.2
          with:
            node-version: ${{ matrix.node }}

        - name: Install Dependencies
          run: npm install

        - name: Generate Website
          run: npm run generate

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Clear the S3 Bucket
          run: aws s3 rm s3://altblu-github-site-62e985645bb9040869013978 --recursive

        - name: Deploy Site to S3 Bucket
          run: aws s3 sync ./dist s3://altblu-github-site-62e985645bb9040869013978
  